name: Deploy Database Migrations
on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v3
            - name: Setup Node
              uses: actions/setup-node@v3
            - name: pnpm-setup
              uses: pnpm/action-setup@v2
            - name: Install dependencies
              run: pnpm install
            - name: Apply all pending migrations to the database
              run: pnpm --filter "@bitspace/web" prisma:migrate:deploy
              env:
                  DATABASE_URL: ${{ secrets.DATABASE_URL }}
